# Generated by Django 4.1.7 on 2023-05-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название комнаты')),
                ('currency', models.CharField(max_length=3, verbose_name='Аббревиатура валюты')),
                ('type_of_competition', models.CharField(choices=[('БИНГО', 'Бинго'), ('ЛОТО', 'Лото')], max_length=5, verbose_name='Тип розыгрыша')),
                ('amount_of_members', models.PositiveIntegerField(verbose_name='Количество участников')),
                ('date', models.DateField(verbose_name='Дата розыгрыша')),
                ('time', models.TimeField(verbose_name='Время розыгрыша')),
                ('win', models.CharField(max_length=200, verbose_name='Выигрыш')),
                ('royalty', models.PositiveIntegerField(verbose_name='Роялти')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.CharField(max_length=200, verbose_name='Комбинация')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='TicketSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raws', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Размер билета',
                'verbose_name_plural': 'Размеры билетов',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.PositiveIntegerField()),
                ('place', models.PositiveIntegerField()),
                ('win_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.ticket')),
            ],
            options={
                'verbose_name': 'Победитель',
                'verbose_name_plural': 'Победители',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.ticketsize', verbose_name='Размер билета'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_ticket_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.ticketsize', verbose_name='Размер билета лотереи'),
        ),
    ]
